#!/bin/bash

PACK_NAME="PNPM"
PACK_CONTENT="Performant NPM"

# Package setup function
pack-setup(){
    echo "installing $PACK_NAME..."
    curl -fsSL https://get.pnpm.io/install.sh | sh

    "$HOME/.local/share/pnpm/pnpm" install-completion bash

    if command -v zsh &>/dev/null; then 
        echo -e "
export PNPM_HOME=\"$HOME/.local/share/pnpm\"
export PATH=\"\$PNPM_HOME:\$PATH\"\n
# PNPM end\n" >> "$HOME/.zshrc"
        echo 'alias pn=pnpm' >> "$HOME/.zshrc"

        # Completions
        . "$HOME/.zshrc"
        pnpm install-completion zsh
        
    fi

    echo "$PACK_NAME installed sucessfully."
}

